name: SiparisSistemi
version: 2.0.0
main: org.larune.siparis.OrderPlugin
api-version: '1.20'
author: MrHistories

depend:
  - Vault

commands:
  siparis:
    description: Siparis menusunu acar
    usage: /siparis
    aliases: [order, market]

permissions:
  siparis.admin:
    default: op
    description: Admin komutlari ve NPC yonetimi
